# DataSet Iris - KNN

In [9]:
# pip install scikit-learn

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [20]:
iris = load_iris()

df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["tipo"] = iris.target

dados_preditivos = df[iris.feature_names]
alvo = df["tipo"]

dados_preditivos_train, dados_preditivos_teste, alvo_train, alvo_teste =  train_test_split(dados_preditivos, alvo, test_size=0.3, random_state=42)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(dados_preditivos_train, alvo_train)

alvo_previsto = knn.predict(dados_preditivos_teste)

acuracia = accuracy_score(alvo_teste, alvo_previsto)

display(f'Precisão do KNN k=3: {acuracia*100:.2f}%')

display(df)

'Precisão do KNN k=3: 100.00%'

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),tipo
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [14]:
display(df.loc[118])

df_final = dados_preditivos_teste
df_final["tipo"] = alvo_previsto

display(df_final)

sepal length (cm)    7.7
sepal width (cm)     2.6
petal length (cm)    6.9
petal width (cm)     2.3
tipo                 2.0
Name: 118, dtype: float64

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),tipo
73,6.1,2.8,4.7,1.2,1
18,5.7,3.8,1.7,0.3,0
118,7.7,2.6,6.9,2.3,2
78,6.0,2.9,4.5,1.5,1
76,6.8,2.8,4.8,1.4,1
31,5.4,3.4,1.5,0.4,0
64,5.6,2.9,3.6,1.3,1
141,6.9,3.1,5.1,2.3,2
68,6.2,2.2,4.5,1.5,1
82,5.8,2.7,3.9,1.2,1
110,6.5,3.2,5.1,2.0,2
12,4.8,3.0,1.4,0.1,0
36,5.5,3.5,1.3,0.2,0
9,4.9,3.1,1.5,0.1,0
19,5.1,3.8,1.5,0.3,0
56,6.3,3.3,4.7,1.6,1
104,6.5,3.0,5.8,2.2,2
69,5.6,2.5,3.9,1.1,1
55,5.7,2.8,4.5,1.3,1
132,6.4,2.8,5.6,2.2,2
29,4.7,3.2,1.6,0.2,0
127,6.1,3.0,4.9,1.8,2
26,5.0,3.4,1.6,0.4,0
128,6.4,2.8,5.6,2.1,2
131,7.9,3.8,6.4,2.0,2
145,6.7,3.0,5.2,2.3,2
108,6.7,2.5,5.8,1.8,2
143,6.8,3.2,5.9,2.3,2
45,4.8,3.0,1.4,0.3,0
30,4.8,3.1,1.6,0.2,0
22,4.6,3.6,1.0,0.2,0
15,5.7,4.4,1.5,0.4,0
65,6.7,3.1,4.4,1.4,1
11,4.8,3.4,1.6,0.2,0
42,4.4,3.2,1.3,0.2,0
146,6.3,2.5,5.0,1.9,2
51,6.4,3.2,4.5,1.5,1
27,5.2,3.5,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
32,5.2,4.1,1.5,0.1,0
142,5.8,2.7,5.1,1.9,2
85,6.0,3.4,4.5,1.6,1
86,6.7,3.1,4.7,1.5,1
16,5.4,3.9,1.3,0.4,0
10,5.4,3.7,1.5,0.2,0

In [23]:
flor_exemplo = pd.DataFrame([[5.9,3.0,5.0,1.8]], columns=iris.feature_names)

display(knn.predict(flor_exemplo))

array([2])